build: question1 question2a question2b question2c

question1:
	gcc question1.c -o question1.o -Wall

question2a:
	gcc question2-a.c -o question2-a.o -Wall

question2b:
	gcc question2-b.c -o question2-b.o -Wall

question2c:
	gcc question2-c.c -o question2-c.o -Wall

clean:
	rm -rf *.o
